java.lang.AssertionError: rhs type is null where rhs is Πα[k]₍ₙ₋₁₎{k=1…p} 	at arb4j@0.85/arb.expressions.nodes.binary.BinaryOperation.typesSymmetryicallyEqual(BinaryOperation.java:232) 	at arb4j@0.85/arb.expressions.nodes.binary.BinaryOperation.type(BinaryOperation.java:248) 	at arb4j@0.85/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:114) 	at arb4j@0.85/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:58) 	at arb4j@0.85/arb.expressions.nodes.unary.When.generate(When.java:193) 	at arb4j@0.85/arb.expressions.Expression.generateEvaluationMethod(Expression.java:930) 	at arb4j@0.85/arb.expressions.Expression.compile(Expression.java:691) 	at arb4j@0.85/arb.expressions.Compiler.express(Compiler.java:134) 	at arb4j@0.85/arb.expressions.Compiler.express(Compiler.java:147) 	at arb4j@0.85/arb.expressions.Compiler.express(Compiler.java:100) 	at arb4j@0.85/arb.expressions.Expression.instantiate(Expression.java:121) 	at arb4j@0.85/arb.functions.Function.express(Function.java:154) 	at arb4j@0.85/arb.functions.real.HypergeometricPolynomialSequence.<init>(HypergeometricPolynomialSequence.java:63) 	at arb4j@0.85/arb.functions.real.HypergeometricFunctionSequenceTest.test3F1(HypergeometricFunctionSequenceTest.java:14) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)