https://github.com/crowlogic/arb4j/issues/356
java.lang.AssertionError: revisit: this either needs to return the
reference to the existing variable or create a new entry for it and then
return the reference, reference=N
	at arb4j@0.88/arb.expressions.Expression.newVariableReference(Expression.java:1334)
	at arb4j@0.88/arb.expressions.Expression.resolveFunctionOrVariableReference(Expression.java:1587)
	at arb4j@0.88/arb.expressions.Expression.evaluate(Expression.java:712)
	at arb4j@0.88/arb.expressions.nodes.nary.NAryOperation.parseEndIndex(NAryOperation.java:543)
	at arb4j@0.88/arb.expressions.nodes.nary.NAryOperation.evaluateRangeSpecification(NAryOperation.java:292)
	at arb4j@0.88/arb.expressions.nodes.nary.NAryOperation.<init>(NAryOperation.java:182)
	at arb4j@0.88/arb.expressions.nodes.nary.Summation.<init>(Summation.java:34)
	at arb4j@0.88/arb.expressions.Expression.evaluate(Expression.java:703)
	at arb4j@0.88/arb.expressions.Expression.exponentiate(Expression.java:809)
	at arb4j@0.88/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:848)
	at arb4j@0.88/arb.expressions.Expression.resolveArithmetic(Expression.java:1494)
	at arb4j@0.88/arb.expressions.Expression.parseRoot(Expression.java:1403)
	at arb4j@0.88/arb.expressions.Compiler.express(Compiler.java:143)
	at arb4j@0.88/arb.expressions.Compiler.express(Compiler.java:157)
	at arb4j@0.88/arb.expressions.Compiler.express(Compiler.java:109)
	at arb4j@0.88/arb.expressions.Expression.instantiate(Expression.java:189)
	at arb4j@0.88/arb.functions.real.RealFunction.express(RealFunction.java:635)
	at arb4j@0.88/arb.functions.real.RealFunction.express(RealFunction.java:630)
	at arb4j@0.88/arb.functions.polynomials.HypergeometricPolynomial.<init>(HypergeometricPolynomial.java:53)
	at arb4j@0.88/arb.functions.polynomials.HypergeometricPolynomialTest.testSum(HypergeometricPolynomialTest.java:44)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)