java.lang.IllegalArgumentException: Error at instruction 31: Cannot pop operand off an empty stack. evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; 00000 R R I I R  :  :    L0 00001 R R I I R  :  :     ALOAD 0 00002 R R I I R  : R  :     GETFIELD nCnMinusOneTimesCn.C : LTwoTimesnPlusαPlusβ; 00003 R R I I R  : R  :     ALOAD 1 00004 R R I I R  : R R  :     CHECKCAST arb/Integer 00005 R R I I R  : R R  :     ALOAD 0 00006 R R I I R  : R R R  :     GETFIELD nCnMinusOneTimesCn.c0 : Larb/Integer; 00007 R R I I R  : R R R  :     ILOAD 3 00008 R R I I R  : R R R I  :     ALOAD 4 00009 R R I I R  : R R R I R  :     CHECKCAST arb/Real 00010 R R I I R  : R R R I R  :     INVOKEVIRTUAL arb/Integer.sub (Larb/Real;ILarb/Real;)Larb/Real; 00011 R R I I R  : R R  :     ILOAD 2 00012 R R I I R  : R R I  :     ILOAD 3 00013 R R I I R  : R R I I  :     ALOAD 0 00014 R R I I R  : R R I I R  :     GETFIELD nCnMinusOneTimesCn.l0 : Larb/Real; 00015 R R I I R  : R R I I R  :     INVOKEVIRTUAL TwoTimesnPlusαPlusβ.evaluate (Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; 00016 R R I I R  : R  :     CHECKCAST arb/Real 00017 R R I I R  : R  :     ALOAD 0 00018 R R I I R  : R R  :     GETFIELD nCnMinusOneTimesCn.l1 : Larb/Real; 00019 R R I I R  : R R  :     INVOKEVIRTUAL arb/Real.set (Larb/Integer;)Larb/Real; 00020 R R I I R  : R  :     ALOAD 1 00021 R R I I R  : R R  :     CHECKCAST arb/Integer 00022 R R I I R  : R R  :     ILOAD 2 00023 R R I I R  : R R I  :     ILOAD 3 00024 R R I I R  : R R I I  :     ALOAD 0 00025 R R I I R  : R R I I R  :     GETFIELD nCnMinusOneTimesCn.l2 : Larb/Real; 00026 R R I I R  : R R I I R  :     INVOKEVIRTUAL TwoTimesnPlusαPlusβ.evaluate (Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; 00027 R R I I R  : R  :     CHECKCAST arb/Real 00028 R R I I R  : R  :     ILOAD 3 00029 R R I I R  : R I  :     ALOAD 4 00030 R R I I R  : R I R  :     CHECKCAST arb/Real 00031 R R I I R  : R I R  :     INVOKEVIRTUAL arb/Real.mul (Larb/Real;ILarb/Real;)Larb/Real; 00032 ?     :     ARETURN 00033 ?     :    L1
	at org.objectweb.asm.util@9.6/org.objectweb.asm.util.CheckMethodAdapter$1.throwError(CheckMethodAdapter.java:489)
	at org.objectweb.asm.util@9.6/org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(CheckMethodAdapter.java:475)
	at org.objectweb.asm@9.6/org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:796)
	at org.objectweb.asm.util@9.6/org.objectweb.asm.util.CheckMethodAdapter.visitEnd(CheckMethodAdapter.java:1044)
	at org.objectweb.asm@9.6/org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:796)
	at arb4j/arb.expressions.trace.FlushingTraceMethodVisitor.visitEnd(FlushingTraceMethodVisitor.java:292)
	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:577)
	at arb4j/arb.expressions.Expression.generate(Expression.java:320)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:146)
	at arb4j/arb.expressions.Compiler.compile(Compiler.java:96)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1246)
	at arb4j/arb.functions.Function.express(Function.java:112)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:80)
	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testC(JacobiPolynomialTest.java:84)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at
instruction 31: Cannot pop operand off an empty stack.
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:279)
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Analyzer.analyzeAndComputeMaxs(Analyzer.java:303)
	at org.objectweb.asm.util@9.6/org.objectweb.asm.util.CheckMethodAdapter$1.visitEnd(CheckMethodAdapter.java:472)
	... 29 more
Caused by: java.lang.IndexOutOfBoundsException: Cannot pop operand off
an empty stack.
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Frame.pop(Frame.java:258)
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:679)
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis@9.6/org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:171)
	... 31 more