java.lang.AssertionError: 1/2 needs some way of knowing that its not being called as part of the body of an evaluate(Real,int order,int bits, C  result) method. Add an initializerBits field and load it instead of its being called from within the initializaer. A boolean state variable can be set in the Expression class and everything will work fine as long as its made note of that it is not threadsafe and synchronizing/cloning would need to be implemented to make it so 	at arb4j/arb.expressions.nodes.unary.LommelPolynomial.initializeSequence(LommelPolynomial.java:65) 	at arb4j/arb.expressions.nodes.unary.LommelPolynomial.lambda$0(LommelPolynomial.java:51) 	at arb4j/arb.expressions.Expression.lambda$10(Expression.java:977) 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) 	at arb4j/arb.expressions.Expression.generateInitializationCode(Expression.java:977) 	at arb4j/arb.expressions.Expression.generateInitializationMethod(Expression.java:998) 	at arb4j/arb.expressions.Expression.generate(Expression.java:737) 	at arb4j/arb.expressions.Expression.defineClass(Expression.java:527) 	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1200) 	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1333) 	at arb4j/arb.functions.Function.instantiate(Function.java:420) 	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:86) 	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:81) 	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:61) 	at arb4j/arb.expressions.ExpressionTest.testLommelPolynomial(ExpressionTest.java:31) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)