java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack Exception Details:   Location:     Ψ.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object; @163: invokestatic   Reason:     Type 'arb/RealQuasiPolynomial' (current frame, stack[4]) is not assignable to 'arb/Real'   Current Frame:     bci: @163     flags: { }     locals: { 'Ψ', 'java/lang/Object', integer, integer, 'java/lang/Object' }     stack: { 'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial', integer }   Bytecode:     0000000: 2ab4 001a 9a00 072a b600 1eb2 0024 2ab4     0000010: 0028 2ab4 002b 2bc0 002d 1d2a b400 30b6     0000020: 0034 2ab4 0037 1d2a b400 3ab6 003d 1d2a     0000030: b400 40b6 0034 1904 c000 13b6 0044 1d2a     0000040: b400 48b6 004c 1d2a b400 4fb6 0053 1d2a     0000050: b400 56b6 005a 2ab4 005d 2ab4 0037 1d2a     0000060: b400 60b6 0063 2bc0 002d 1d2a b400 66b6     0000070: 0069 1d2a b400 6cb6 006f 2ab4 0072 592a     0000080: b400 282b c000 2d1d 2ab4 0075 b600 34b2     0000090: 0024 1d2a b400 78b6 007b 1904 c000 13b6     00000a0: 0044 1db8 0081 1d19 04c0 0013 b600 82b0     00000b0:   Stackmap Table:     same_frame(@11)
	at arb4j/arb.utensils.Utensils.wrapOrThrow(Utensils.java:693)
	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1228)
	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1345)
	at arb4j/arb.RealQuasiPolynomialTest.testQuasi(RealQuasiPolynomialTest.java:36)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177)
	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142)
	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125)
	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130)
	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236)
	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Ψ.evaluate(Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;
@163: invokestatic
  Reason:
    Type 'arb/RealQuasiPolynomial' (current frame, stack[4]) is not
assignable to 'arb/Real'
  Current Frame:
    bci: @163
    flags: { }
    locals: { 'Ψ', 'java/lang/Object', integer, integer,
'java/lang/Object' }
    stack: { 'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial',
'arb/RealQuasiPolynomial', 'arb/RealQuasiPolynomial',
'arb/RealQuasiPolynomial', integer }
  Bytecode:
    0000000: 2ab4 001a 9a00 072a b600 1eb2 0024 2ab4
    0000010: 0028 2ab4 002b 2bc0 002d 1d2a b400 30b6
    0000020: 0034 2ab4 0037 1d2a b400 3ab6 003d 1d2a
    0000030: b400 40b6 0034 1904 c000 13b6 0044 1d2a
    0000040: b400 48b6 004c 1d2a b400 4fb6 0053 1d2a
    0000050: b400 56b6 005a 2ab4 005d 2ab4 0037 1d2a
    0000060: b400 60b6 0063 2bc0 002d 1d2a b400 66b6
    0000070: 0069 1d2a b400 6cb6 006f 2ab4 0072 592a
    0000080: b400 282b c000 2d1d 2ab4 0075 b600 34b2
    0000090: 0024 1d2a b400 78b6 007b 1904 c000 13b6
    00000a0: 0044 1db8 0081 1d19 04c0 0013 b600 82b0
    00000b0:
  Stackmap Table:
    same_frame(@11)

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)
	at java.base/java.lang.Class.getConstructor0(Class.java:3754)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1224)
	... 19 more