The error occurs because `setClassesDir()` is deprecated and removed in newer Gradle versions. Here's the correct way to set the output directories:
```groovy
sourceSets {
    main {
        java.destinationDirectory.set(file('bin/main'))
        output.resourcesDir = file('bin/main')
    }
    test {
        java.destinationDirectory.set(file('bin/test'))
        output.resourcesDir = file('bin/test')
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}
```

The key difference is using `java.destinationDirectory.set()` instead of
the deprecated `setClassesDir()` method[1][2]. This is the modern way to
configure output directories in Gradle while maintaining compatibility
with newer versions.

Citations:
[1] https://discuss.gradle.org/t/gradle-4-sourcesetoutput-setclassesdir-deprecated/23044
[2] https://discuss.gradle.org/t/seeing-nosuchmethoderror-on-deprecated-methods-of-gradle-4-api/23026
[3] https://stackoverflow.com/questions/44578302/splitting-all-output-directories-in-gradle
[4] https://discuss.gradle.org/t/why-am-i-getting-a-could-not-find-method-error-when-trying-to-use-an-extension-after-adding-it-in-custom-plugin-development/46828
[5] https://www.chiefdelphi.com/t/gradle-plugin-issues/401382