java.lang.AssertionError: generate the instructions to get call getClass(), construct a new instance using the copy-constructor so that the field values are assigned properly,  this=FunctionCall[name=P, function=Mapping[name=P, func=null, domain=arb.Integer, range=arb.RealPolynomial, functionInterface=null], arg=n - 1, targetResultType=arb.RealPolynomial] 	at arb4j/arb.expressions.nodes.unary.FunctionCall.generateContextualFunctionCall(FunctionCall.java:191) 	at arb4j/arb.expressions.nodes.unary.FunctionCall.generate(FunctionCall.java:115) 	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:98) 	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:97) 	at arb4j/arb.expressions.nodes.binary.BinaryOperation.generate(BinaryOperation.java:97) 	at arb4j/arb.expressions.nodes.unary.UnaryOperation.generate(UnaryOperation.java:73) 	at arb4j/arb.expressions.nodes.unary.When.generate(When.java:78) 	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:473) 	at arb4j/arb.expressions.Expression.generate(Expression.java:369) 	at arb4j/arb.expressions.Compiler.compile(Compiler.java:101) 	at arb4j/arb.expressions.Compiler.compile(Compiler.java:75) 	at arb4j/arb.expressions.Expression.instantiate(Expression.java:117) 	at arb4j/arb.functions.Function.express(Function.java:147) 	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialSequence.<init>(JacobiPolynomialSequence.java:103) 	at arb4j/arb.functions.polynomials.orthogonal.JacobiPolynomialTest.testP0(JacobiPolynomialTest.java:139) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)