414arb.exceptions.UndefinedReferenceException: Undefined reference to variable 'y' in expression=n➔½*√(2*(4*n+1)/y)*(-1)^n*J(2*n+½,y), expression.rootNode=null, independent variable is n and parentExpression is null 	at arb4j/arb.expressions.nodes.Variable.resolveInheritedVariableReference(Variable.java:486) 	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:418) 	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:150) 	at arb4j/arb.expressions.Expression.newVariable(Expression.java:1466) 	at arb4j/arb.expressions.Expression.resolveSymbolicLiteralConstantsKeywordsAndVariables(Expression.java:1775) 	at arb4j/arb.expressions.Expression.resolveIdentifier(Expression.java:1755) 	at arb4j/arb.expressions.Expression.evaluate(Expression.java:576) 	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:695) 	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:1413) 	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:726) 	at arb4j/arb.expressions.Expression.resolve(Expression.java:1666) 	at arb4j/arb.expressions.Expression.resolveFunction(Expression.java:1739) 	at arb4j/arb.expressions.Expression.resolveIdentifier(Expression.java:1751) 	at arb4j/arb.expressions.Expression.evaluate(Expression.java:576) 	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:695) 	at arb4j/arb.expressions.Expression.multiplyAndDivide(Expression.java:1406) 	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:726) 	at arb4j/arb.expressions.Expression.resolve(Expression.java:1666) 	at arb4j/arb.expressions.Expression.parseRoot(Expression.java:1551) 	at arb4j/arb.functions.Function.parse(Function.java:395) 	at arb4j/arb.RealQuasiPolynomial.parseSequence(RealQuasiPolynomial.java:31) 	at arb4j/arb.RealQuasiPolynomial.parseSequence(RealQuasiPolynomial.java:25) 	at arb4j/arb.RealQuasiPolynomialTest.testQuasi(RealQuasiPolynomialTest.java:20) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:757) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)