java.lang.NullPointerException: Cannot load from object array because "this.rows" is null 	at arb4j/arb.RealMatrix.getRow(RealMatrix.java:104) 	at arb4j/arb.RealMatrix.set(RealMatrix.java:68) 	at arb4j/arb.Integer.add(Integer.java:310)