arb.exceptions.UndefinedReferenceException: Undefined reference to variable 'k' in Expression[expression=n➔∏k₍ₙ₋₁₎{k=1…3}, className=n∏k₍ₙ₋₁₎{k=1…3}, functionName=null, recursive=false, functionClass=interface arb.functions.Function], independent variable is Variable[reference=INPUT(n), type=arb.Integer] and containingExpression is null 	at arb4j/arb.expressions.nodes.Variable.resolveReference(Variable.java:259) 	at arb4j/arb.expressions.nodes.Variable.<init>(Variable.java:112) 	at arb4j/arb.expressions.Expression.newVariable(Expression.java:1192) 	at arb4j/arb.expressions.Expression.resolveFunctionOrVariableReference(Expression.java:1356) 	at arb4j/arb.expressions.Expression.evaluate(Expression.java:493) 	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:620) 	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:659) 	at arb4j/arb.expressions.Expression.determine(Expression.java:453) 	at arb4j/arb.expressions.nodes.nary.Product.evaluateRangeSpecification(Product.java:167) 	at arb4j/arb.expressions.Expression.evaluate(Expression.java:484) 	at arb4j/arb.expressions.Expression.exponentiate(Expression.java:620) 	at arb4j/arb.expressions.Expression.exponentiateMultiplyAndDivide(Expression.java:659) 	at arb4j/arb.expressions.Expression.determine(Expression.java:453) 	at arb4j/arb.expressions.Expression.parse(Expression.java:612) 	at arb4j/arb.expressions.Compiler.express(Compiler.java:134) 	at arb4j/arb.expressions.Compiler.express(Compiler.java:147) 	at arb4j/arb.expressions.Compiler.express(Compiler.java:100) 	at arb4j/arb.expressions.Expression.instantiate(Expression.java:121) 	at arb4j/arb.functions.Function.express(Function.java:161) 	at arb4j/arb.functions.Function.express(Function.java:175) 	at arb4j/arb.expressions.ExpressionTest.testParentExpressionInputToSubexpression(ExpressionTest.java:15) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)