java.lang.AssertionError:  TODO: check left and right for the need to cast 	at arb4j/arb.expressions.nodes.BinaryOperation.generate(BinaryOperation.java:74) 	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:517) 	at arb4j/arb.expressions.Expression.generate(Expression.java:305) 	at arb4j/arb.expressions.Compiler.compile(Compiler.java:121) 	at arb4j/arb.expressions.Compiler.compile(Compiler.java:71) 	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1198) 	at arb4j/arb.functions.real.RealFunction.express(RealFunction.java:612) 	at arb4j/arb.expressions.RealFunctionExpressionCompilerTest.testFunctionInvolvingABesselFunction(RealFunctionExpressionCompilerTest.java:144) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)