java.lang.AssertionError: TODO: tried to return class java.lang.Object for x which is part of DerivativeNode[operand=(a*x+(b*x^2))+(c*x^3), variable=x, derivative=((0*x+a*1)+((0*x^2)+(b*x^2)))+((0*x^3)+(c*x^3))] 	at arb4j/arb.expressions.nodes.VariableNode.type(VariableNode.java:592) 	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.type(BinaryOperationNode.java:363) 	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.type(BinaryOperationNode.java:362) 	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.type(BinaryOperationNode.java:362) 	at arb4j/arb.expressions.nodes.binary.BinaryOperationNode.generate(BinaryOperationNode.java:190) 	at arb4j/arb.expressions.nodes.DerivativeNode.generate(DerivativeNode.java:141) 	at arb4j/arb.expressions.Expression.generateEvaluationMethod(Expression.java:940) 	at arb4j/arb.expressions.Expression.generate(Expression.java:787) 	at arb4j/arb.expressions.Expression.defineClass(Expression.java:570) 	at arb4j/arb.expressions.Expression.getInstance(Expression.java:1218) 	at arb4j/arb.expressions.Expression.instantiate(Expression.java:1367) 	at arb4j/arb.functions.Function.instantiate(Function.java:126) 	at arb4j/arb.functions.rational.RationalNullaryFunction.express(RationalNullaryFunction.java:29) 	at arb4j/arb.functions.rational.RationalNullaryFunction.express(RationalNullaryFunction.java:39) 	at arb4j/arb.RationalFunction.express(RationalFunction.java:245) 	at arb4j/arb.expressions.ExpressionTest.testRationalFunctionDerivative(ExpressionTest.java:83) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) 	at junit@4.13.2/junit.framework.TestCase.runTest(TestCase.java:177) 	at junit@4.13.2/junit.framework.TestCase.runBare(TestCase.java:142) 	at junit@4.13.2/junit.framework.TestResult$1.protect(TestResult.java:122) 	at junit@4.13.2/junit.framework.TestResult.runProtected(TestResult.java:142) 	at junit@4.13.2/junit.framework.TestResult.run(TestResult.java:125) 	at junit@4.13.2/junit.framework.TestCase.run(TestCase.java:130) 	at junit@4.13.2/junit.framework.TestSuite.runTest(TestSuite.java:241) 	at junit@4.13.2/junit.framework.TestSuite.run(TestSuite.java:236) 	at junit@4.13.2/org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:530) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:758) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:453) 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)
	https://github.com/crowlogic/arb4j/issues/253